# Importing Libraries

In [1]:
# libraries for automating the data analysis process

import os 
from glob import glob
import re

# libraries for data analysis

import pandas as pd
from fuzzywuzzy import fuzz

# Defining Folder Variables

In [2]:
# Set relative paths for different folders
MAIN_FOLDER = os.path.abspath(os.path.join(os.getcwd(), ".."))

CODE_FOLDER = os.path.join(MAIN_FOLDER, "Code")

PROFILE_FOLDER = os.path.join(CODE_FOLDER, "ProfileReports")

DATA_FOLDER = os.path.join(MAIN_FOLDER, "Data")

RAW_SHEETS_FOLDER = os.path.join(DATA_FOLDER, "Raw_Sheets")

CLEANED_SHEETS_FOLDER = os.path.join(DATA_FOLDER, "Cleaned_Sheets")

# Defining Sheet Variables

In [3]:
SAVE_TO_CSV = os.path.join(CLEANED_SHEETS_FOLDER, "cleaned_sheet.csv")

FINAL_SHEET = os.path.join(CLEANED_SHEETS_FOLDER, "powerbi_analysis.csv")

# Loading Data

In [4]:
df = pd.read_csv(SAVE_TO_CSV)

df

,OrderNumber,CUSTID,JOBTYPE,Department,FROMLOCSTR,TOLOCSTR,STARTTM,ENDTM,TripDuration,CTCOMPLETEDT,DriverId,PrimeMoverId,TrailerId,JOINED DATE,RESIGNED DATE,RACE,Team,Status,AGE_Years,Seniority
0,TL9008453,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-07 08:00:00,2021-01-07 08:30:00,0.500000,2021-01-07,2,215,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,16.0,53.58,13.72
1,TL9008453,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-07 10:30:00,2021-01-07 11:00:00,0.500000,2021-01-07,2,215,972.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,16.0,53.58,13.72
2,TL9009105,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-27 08:00:00,2021-01-27 08:30:00,0.500000,2021-01-27,2,215,972.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,6.0,53.58,13.72
3,TL9009105,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-27 10:30:00,2021-01-27 11:00:00,0.500000,2021-01-27,2,215,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,6.0,53.58,13.72
4,TL9008550,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-11 08:00:00,2021-01-11 08:30:00,0.500000,2021-01-11,2,215,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,13.0,53.58,13.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1081779,TE8037442,00-RA186,EXPORT,MAIN,PTC48(G),42PANDAN1,2023-12-06 09:50:00,2023-12-06 10:00:00,0.166667,2023-12-06,220,222,1772.0,2008-03-17,2023-12-31,CHINESE,FCL,34.0,51.33,15.79
1081780,TL9050450,00-RA186,LOCAL,CHIEN,COGENT TANK 15,48DRUMMING,2023-12-04 10:30:00,2023-12-04 12:00:00,1.500000,2023-12-04,37,145,119.0,2004-06-25,2023-12-31,CHINESE,CHIEN LI,8.0,68.25,19.52
1081781,TL9050450,00-RA186,LOCAL,CHIEN,48DRUMMING,STOLT NEL,2023-12-06 05:39:00,2023-12-06 05:59:00,0.333333,2023-12-06,302,394,119.0,2008-08-22,2023-05-10,CHINESE,CHIEN LI,21.0,39.08,14.71
1081782,TE8037521,00-RA186,EXPORT,MAIN,42PANDAN1,PSA/PPT,2023-12-13 09:30:00,2023-12-13 10:30:00,1.000000,2023-12-13,110,424,1937.0,2000-11-20,2022-10-02,CHINESE,FCL,8.0,58.92,21.86
1081783,XE7047519,00-RP036,EXPORT,XINHUA,CONT CONN,PTC MER-GROUND,2023-12-29 00:00:00,2023-12-29 00:00:00,0.000000,2023-12-29,0,1001,NaN,NaN,2023-12-31,NaN,NaN,NaN,NaN,NaN

# Fuzzy String Matching Algorithm

## Preprocessing Strings via Regex

In [5]:
# first use regex to replace all non-alphanumeric characters with a space

def preprocess_street_name(name):
    """
    Preprocess the street name by removing special characters.
    """

    pattern = r'[^A-Za-z0-9\s]'  # Matches any character that is not a letter, digit, or whitespace
    
    # replace non- letter, digit, or whitespace with a space
    cleaned_name = re.sub(pattern, ' ', name)
    
    return cleaned_name

df['FROMLOCSTR'] = df['FROMLOCSTR'].apply(lambda x: preprocess_street_name(x))
df['TOLOCSTR'] = df['TOLOCSTR'].apply(lambda x: preprocess_street_name(x))

df.head(-10)

,OrderNumber,CUSTID,JOBTYPE,Department,FROMLOCSTR,TOLOCSTR,STARTTM,ENDTM,TripDuration,CTCOMPLETEDT,DriverId,PrimeMoverId,TrailerId,JOINED DATE,RESIGNED DATE,RACE,Team,Status,AGE_Years,Seniority
0,TL9008453,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-07 08:00:00,2021-01-07 08:30:00,0.5,2021-01-07,2,215,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,16.0,53.58,13.72
1,TL9008453,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-07 10:30:00,2021-01-07 11:00:00,0.5,2021-01-07,2,215,972.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,16.0,53.58,13.72
2,TL9009105,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-27 08:00:00,2021-01-27 08:30:00,0.5,2021-01-27,2,215,972.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,6.0,53.58,13.72
3,TL9009105,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-27 10:30:00,2021-01-27 11:00:00,0.5,2021-01-27,2,215,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,6.0,53.58,13.72
4,TL9008550,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-11 08:00:00,2021-01-11 08:30:00,0.5,2021-01-11,2,215,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,13.0,53.58,13.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1081769,XI7007593,00-RE114,IMPORT,XINHUA,31GUL CR,14 PENJ RD,2023-12-12 08:30:00,2023-12-12 09:30:00,1.0,2023-12-12,169,296,1771.0,2007-12-01,2023-12-31,CHINESE,Team 1,13.0,55.33,16.08
1081770,XI7007593,00-RE114,IMPORT,XINHUA,14 PENJ RD,EKY2,2023-12-12 09:30:00,2023-12-12 10:00:00,0.5,2023-12-12,169,296,1771.0,2007-12-01,2023-12-31,CHINESE,Team 1,13.0,55.33,16.08
1081771,XI7007610,00-RE114,IMPORT,XINHUA,PSA PPT,PTC ISL G,2023-12-12 09:00:00,2023-12-12 10:00:00,1.0,2023-12-12,379,338,1499.0,2014-11-01,2023-12-31,MALAY,Team 1,9.0,55.08,9.16
1081772,XI7007610,00-RE114,IMPORT,XINHUA,PTC ISL G,CWT47JLNBUROH,2023-12-13 11:00:00,2023-12-13 12:00:00,1.0,2023-12-13,356,336,1934.0,2012-08-24,2023-12-31,MALAY,Team 1,8.0,37.42,11.35
1081773,XI7007622,00-RE114,IMPORT,XINHUA,PSA PPT,PTC ISL G,2023-12-21 07:30:00,2023-12-21 08:30:00,1.0,2023-12-21,169,296,1265.0,2007-12-01,2023-12-31,CHINESE,Team 1,8.0,55.33,16.08

# Current # of FROMLOCSTR

In [6]:
df['FROMLOCSTR'].nunique()

483

In [7]:
df['FROMLOCSTR'].unique()

array(['JI DRUM', '1 SEARAYA', 'J ISLAND', '1 SERAYA AVE', 'ISLAND G ',
       '31 AYER', '31AYERMBRD', '2 SERAYA P', 'STOLT NEL', '2SERAYA PL',
       'MER GROUND', 'PTCISLAND', 'NX5', '48DRUMMING', '2SERAYA RI',
       'JOO LONG', '35SHIPYARD', '1 TUAS', '18 PIONEER', '39 SHIPYAR',
       'P A C', 'STOLTNEL', '2 BANYAN', '1SAKRAVE', '38 GUL', 'TPC',
       'DPONTSKR', '59PENJURU', '250 ISLAND', '30 GULCRES', '162 GUL',
       '14TUAS DR2', '800 SUPER', 'CONT CONN', 'EKY2', 'ITS 23PIOSEC',
       'GREENEARTH', '5 SGKADUT', 'PTC ISLAND', 'INF PAC', '41 TUASCRE',
       '10 TAMPINE', 'NTH COAST', '21 J BUROH', '60WOODLAND', 'EXXON PAC',
       '21 J PORT', '19B JGPIER', '46TUASCRES', '21GUL LANE', 'EXXONPAC',
       '28GULCRES', '5JLN BESUT', '5 TG PENJ', '20PENJURU', '15TEMBUSU',
       '20 BANYAN', 'CWT INT', '21SAKRA', '39SHIPYARD', 'PTCMRTGR',
       'JPEIRCP', 'ITS 162', '48 PTC', '210JLNBROH', '1 BUROH',
       'PACIFICTRA', 'OCW3', 'ALLIED 8', 'CWT 24 P C', 'PTCISL OFF',
       'PPT', '48PANDAN', 'TOTAL TUAS', 'ALLIED 3', '42PTC', 'EK TUAS S',
       'PTC48 G ', 'PTCJIDRUMM', '2 TUAS S S', '2 TUAS S', 'ITALSING',
       '42PANDAN6', '100 JI', 'JURONG', 'S GOON NTH', 'ANX5', '10 TEPONG',
       '210CALTEX', '150TUASSTH', '1B SAKRA', '1 ISLAND', '23 TEMBUSU',
       '14 PENJ RD', '150 TUAS', '23TG KLING', '61SERAYAVE', '121 BANYAN',
       'PTC MYD', '61SERAYAAV', '5 TUAS VIE', '180 GUL', 'EMPL PAM',
       '9TUASVIEWL', '14TUASAV20', '9 TUAS V L', 'GROUNDNLIFT',
       '34TUASAV8', 'SHELL TUAS', 'SINOPEC', '19TRACTOR', 'HIN LEONG',
       'OCW1', 'EKY PIONEE', 'PTCMRTPK', 'STOLT GRP', '39 TUAS',
       '31GUL CRES', '100 PAM', '31 GULCRES', '31GULCRESC', '14PENJURUR',
       '22TEMBUSU', 'EKY1', 'GRANGE RD', 'PEARMORE', 'EKY SOUTH',
       'TONG 2', 'CHUAN LI Y', 'PAC TRANS', '42PANDAN7', '42PANDAN2',
       '4 BENOI RD', '21PANDANRD', 'PTC ISLWH', '11CLEMENTI', '42PANDAN4',
       '31GUL CR', 'JOOKOONCR', '42PANDAN3', 'PTC JI', 'ISLD RTG  G ',
       '42 PANDAN', '8TUASBL', 'B TIMAH', '39TUASCRES', '31 GUL CRE',
       'PSA DEPOT', 'PANDAN DR', 'CHANGI', 'FARRER RD', 'BT', 'PSA TPT',
       '25 GREEN', 'PAC', 'HLA LOGIST', 'ISLANDPARK', '101SAKRA',
       'PTCMYD', '6 LOKYANG', 'TONG CONT2', 'INF PAC1', 'KT', 'TPC1',
       '25SENOKO', '14PENJUR', 'E K PION', 'HLA', 'TPC2', 'WINGSENG',
       'ALLIED 5', 'ACW2', '31 TUA SOU', '231PANDANL', '38TGPENJUR',
       '118 PION R', '1TUASSOUTH', 'SERANGOON', 'EAST COAST',
       '38 PENJURU', 'COG TANK', '6 TUAS SOU', 'PSA JIT', 'TOLL LOG',
       'HILLVIEW', 'ALLIED 2', 'PSA CD', '48TOH GUAN', '31TUAS S',
       '16TUASVIEWC', 'PIONEER YD', '38 PEN LAN', 'COGENT T C', 'HLA2',
       '34 TUAS', 'PAM', '7 GUL DR', 'OCW 3', '30SKRAVIEW', 'HB CCK',
       'CHUAN LI', '8 GUL RD', '37 TUAS RD', 'PCS ISLAND', 'PTC48 PARK',
       '500 AYER', '10TUASSOUT', '21 JOO KOO', 'ETPC2', '10SAKRAVE',
       '17SAKRRD', '17 SAKRA', '2TUASLOOP', '1 SERAYA P', 'CWT DEPOT',
       'BEE JOO', '24 JURONG', '12 TUAS2', '213PANDAN', '50TUASAVE1',
       'ALLIED 1', 'ORCHARD', 'HLA2 HTS2', '31PENJURUL', '14TUASDR2',
       '3A J TERUS', 'MERANTI AV', 'CONT CONNE', 'UNITED OIL', 'MLO PAC',
       '20PENJURUL', '3 PASIR RI', '22B BENOI', '6 ATTAP V', '5TUASVL',
       'AP OIL 18', 'PTCISL TT', '31 GUL', '18 PION RD', '18GULCRES',
       'CWT HUB1', '8TUASBLK', '21TG KLING', 'TUASSAVE4', '46 GUL CRE',
       '11 TUAS V', 'PSA BT', '31 TUAS', '8 JURONG P', '1 BUROH LN',
       'COGENT CS', 'SENKEE', 'SH COGENT', 'KD', '1 HARBOURF',
       'NEWTON RD', 'TAMPINES', '8 TUALINK', 'TPJPEIRCPC', '24JRPORT',
       '10A TUAS', '26 TG KLIN', '51 BANYAN', 'VOPAK SAKR', 'HB 48P',
       '12 SAKRA', '52 S KADUT', 'ECO', '48 TUAS', '20TUAS ST',
       '18PIONEER', 'LIKOK', '100 BANYAN', '7GULDRIVE', 'COGENT TEM',
       'ACW 2', '17TUASVWCIR', '21PANDANAV', '14TUAS', '8GUL RD',
       '300 AYER M', 'EXXONMOBIL', 'TBS STOLT', '60 TUAS', '9B J PIER',
       'PTCJI WH', 'ECO TUAS', 'ISLAND PAC', '18TUASLINK', 'EXXONBILL',
       '3PASIRRISD12', '24PENJURUR', '1TUAS', '14 TUAS', '10TAMPINES',
       'ECOLAB', '132PIONEER', '41TUASROAD', '9TUASBASINLNK',
       '21SKARAAVE', '4BENOIRD', '9TUASAVE10', '11 TUAS', '6TUAS',
       '39BENOIRD', '9 CHIN BEE', '10TUAS AVE', '10 TUAS', '5 TUAS AVE',
       '47JLNBUROH', '42C PENJR', 'PSA W HSE', '5TUAS VIEW', '47A JBUROH',
       'CWT JALAN', 'PPW', 'YARD 3', '10TUASAVE13', '18PIONEER ',
       '8 BENOI', 'MBS SKRA', '23TEMBUSURD', '38GULAVE', '11TUASAVE11',
       '38GUL AVE', '9 PIONEER', '31 JURONG', '31JUR PORT', '7 GUL CIR',
       '39AYERMERD', '4 BENOI', 'YANGKEE', '47AJLNBURO', '37TUAS',
       '47AJLN BUR', '76PIONERRD', 'MYDTR', '9KALLANGSEC', 'AIK MOH',
       '31J PORT', 'NRS W HSE', '16 TUAS A5', 'PPT CD', 'W SHOP JI',
       '6TUAS AVE1', '31JPORT 04', '49PANDAN 03 02', '19TUAS',
       '40PANDANRD', '43GULDRIVE', '21 LYANG', '701AYERMER', '30 PIONEER',
       '76 PIONEER', '24PENJURU', '20 TUAS 13', '20TUAS13', 'PTCJID',
       '5ATOHGUANRD', 'ODSA PAC', '8 TUAS', '18 ENTERP', 'ISLAND HUB',
       'SK YAP', '58TUASBAS', 'VOPAK PJ', '9 J PIER 1', '42PANDAN1',
       '9PIONEERVW', '24JURPORT', 'PSATUAS', '42PANDAN5', 'ETPC1',
       'SUMITOMO', '37 TUAS', '76PIONEER', 'HB CLMTI', '6 TUAS AVE',
       '180GUL CIR', 'JIDTR', '1 BANYAN P', '20 TUAS', '20TUAS',
       'ITS YARD', '2SERAYA RI 2', '23TUAS', 'JITERMINAL', 'CDC CLEMEN',
       '37TUASAVE8', '6TUASAVE2', '47TUASVIEW', '75TUASSOUTH',
       '33PENJURUL', 'TEMBUSU', '1 TUASBAYCLOSE', 'GREEN Y2', '33PENJURU',
       '33 PENJURU', '35TUASRD', '23 TUAS', '1 BANYAN', '37TUASAVE2',
       '16 TUAS', '39B JLN', 'AVE 7', '30PIONEERD', '6 FISHERY',
       'JOO KOON', 'JI OFFLOAD', '019 GUL LA', '24P JURU PSA', '18PIONRD',
       'PPT W S ', 'GKE', 'ENTERPRISE', '50TUASAVE9', 'COGENT JI',
       'SKY COGENT', 'PSA PPT', 'CWT PIONEER', 'CWT TUAS', 'PSA TUAS',
       'PSA BT KT', 'BUROH STRT', '352BOONLAY', '48TOHGUADR',
       '7 TUAS A14', 'CWT47JLNBUROH', '9GULCIRCLE', '11TUASLINK1',
       '1BANYAN P', 'CANCEL TRIP', '1TEMBUSUCR', 'PTC JID', 'PTC ISL  G ',
       'PTC MER GROUND', 'PTC MER PARK', 'COGENT TANK 15', 'HB NX5',
       'CARPARK C  NX5 ', 'PTC ISLAND PARK', 'JI W SHOP',
       'COGENT TEMBUSU', 'GREASE PL', 'JURONGISL', 'STARTFIRST',
       '11SCIENCEP', '21PIONEERS', '1PANDAN RD', 'PPW BLK2',
       'CARPARK C NX5 ', 'TRANSIT PANDAN', '25 SENOKO', '1 ANGSANA',
       '2BUROHCRESCENT', 'SKY COG LOGIST', '21 BANYAN', '8 10 GUL',
       'TONGCNTR', 'COGENT BANYAN', '7 GUL AVE', 'SILTRONICSILI',
       'SHELLPANDAN', '21 GUL AVE', '10 PANDAN', '31 GUL CIR',
       'HEANNERNG', '200AYERMB', 'PTC ISLAND  SHED ', 'LHNLOGISTICS',
       'FAIRCHEM', '35 KIAN TE', 'TPC2 G ', 'TPC1 G ', 'POSAN YARD',
       'CWT HUB', 'PSASEMBAWA', 'MATCHBOX', 'CONTCONN', '11 JLN TER',
       '52TG PENJ', '52 TG  PEN', '1SENOKOAVE'], dtype=object)

# Current # of TOLOCSTR

In [8]:
df['TOLOCSTR'].nunique()

493

In [9]:
df['TOLOCSTR'].unique()

array(['1 SERAYA AVE', '31 AYER', '5 SGKADUT', 'J ISLAND', 'JI DRUM',
       'ISLAND G ', 'MER GROUND', '1 SEARAYA', '31AYERMBRD', '48DRUMMING',
       '2SERAYA RI', 'JOO LONG', '2SERAYA RI 2', 'STSS', 'STOLT NEL',
       '39 SHIPYAR', 'P A C', 'PTC ISLAND', 'PTCISLAND', 'TPC',
       '250 ISLAND', '1 SERAYA P', '1 TUAS', '1SAKRAVE', '2 BANYAN',
       '38 GUL', '35SHIPYARD', '59PENJURU', '15TEMBUSU', '800 SUPER',
       'OCW3', 'NX5', '30 GULCRES', '14TUAS DR2', '162 GUL', 'CONT CONNE',
       'CONT CONN', 'ECO', 'GREENEARTH', 'EKY2', '39SHIPYARD',
       '210CALTEX', 'KT', '10TAMPINES', '19B JGPIER', '21 J BUROH',
       'NTH COAST', 'INF PAC', 'ANX5', 'EXXONPAC', 'EXXON PAC',
       '21 J PORT', '150TUASSTH', '5JLN BESUT', '20PENJURU', '21GUL LANE',
       '28GULCRES', 'PSA TPT', '20 BANYAN', '5 TG PENJ', 'DPONTSKR',
       'CWT INT', '48 PTC', 'ITS 162', 'JPEIRCP', 'PTCMRTGR', '21SAKRA',
       '42 PANDAN', 'PTC48 PARK', 'PTCISL OFF', 'PPT', 'BT', '42PTC',
       '210JLNBROH', 'TOTAL TUAS', '48PANDAN', 'EXXONBILL', 'STOLTNEL',
       '46TUASCRES', 'PTC48 G ', 'STOLT GRP', 'PTCJIDRUMM', '2SERAYA PL',
       'MERANTI AV', 'COGENT T C', '2 TUAS S S', '2 TUAS S', '100 JI',
       '18 PIONEER', '42PANDAN6', 'JURONGISL', 'S GOON NTH', '10 TEPONG',
       '1 ISLAND', '60WOODLAND', '23 TEMBUSU', '14 PENJ RD', '10 TAMPINE',
       '41 TUASCRE', 'ITALSING', '180 GUL', '150 TUAS', '23TG KLING',
       '61SERAYAVE', '5 TUAS VIE', 'EMPL PAM', 'GROUNDNLIFT',
       '9TUASVIEWL', '14TUASAV20', '34TUASAV8', '2 SERAYA P', 'SINOPEC',
       'SHELL TUAS', '19TRACTOR', 'HIN LEONG', 'PTCMRTPK', '121 BANYAN',
       '16TUASVIEWC', '39 TUAS', 'ALLIED 8', '100 PAM', '31 GULCRES',
       'EKY1', '31GULCRESC', '14PENJURUR', '22TEMBUSU', 'GRANGE RD',
       'PEARMORE', '4 BENOI RD', '21PANDANRD', 'ALLIED 3', 'PSA JIT',
       'PSA BT', 'SK YAP', '1 BUROH', 'ACW2', 'JOOKOONCR', '42PANDAN3',
       'PTC JI', 'EKY SOUTH', 'PAC TRANS', 'ALLIED 5', 'B TIMAH',
       'EK TUAS S', 'HLA2', 'ST', '42PANDAN2', '42PANDAN4', '39TUASCRES',
       'OCW1', 'PANDAN DR', 'CHANGI', 'FARRER RD', 'PAC', '8TUASBL',
       '11CLEMENTI', 'ISLANDPARK', 'TONG 2', 'PTCMYD', '6 LOKYANG',
       '15TUASAV12', 'PACIFICTRA', 'ALLIED 2', 'INF PAC1', 'TPC1',
       '42PANDAN7', '25SENOKO', '14PENJUR', '25 GREEN', '9 TUAS V L',
       'TPC2', 'EKY PIONEE', '31 TUA SOU', '231PANDANL', '38TGPENJUR',
       'CWT DEPOT', '31 GUL CRE', 'PSA DEPOT', '1TUASSOUTH', 'SERANGOON',
       'EAST COAST', 'PTC ISLWH', '31GUL CR', '38 PENJURU', '6 TUAS SOU',
       '118 PION R', 'CWT 24 P C', 'TOLL LOG', 'HILLVIEW', 'PSA CD',
       '48TOH GUAN', 'PTC MYD', '31TUAS S', '38 PEN LAN', '34 TUAS',
       'PAM', '7 GUL DR', '30SKRAVIEW', '27BENOI', 'HB CCK', '8 GUL RD',
       'HLA LOGIST', '101SAKRA', '37 TUAS RD', 'PCS ISLAND', '500 AYER',
       'CHUAN LI Y', 'UNKNOWN', 'LIKOK', 'JURONGPT', '21 JOO KOO',
       'ETPC2', '10SAKRAVE', 'HLA', '17 SAKRA', '17SAKRRD', '2TUASLOOP',
       'JURONG', 'SH COGENT', 'HLA2 HTS2', '18 PION RD', 'BEE JOO',
       '24 JURONG', 'EXXONMOBIL', '14PIO SEC2', 'WINGSENG', '213PANDAN',
       '50TUASAVE1', '10TUASAV13', 'ORCHARD', '31PENJURUL', '14TUASDR2',
       '3A J TERUS', 'UNITED OIL', 'MLO PAC', '20PENJURUL', '3 PASIR RI',
       '6 ATTAP V', 'OCW 3', '5TUASVL', 'AP OIL 18', '31 GUL',
       '18GULCRES', 'CWT HUB1', '8TUASBLK', '22B BENOI', '21TG KLING',
       '1 BUROH LN', 'TUASSAVE4', '46 GUL CRE', '11 TUAS V', 'PPT CD',
       'COGENTISLD', '31 TUAS', '12 TUAS CR', '8 JURONG P', '42C PENJR',
       'SENKEE', '1 HARBOURF', 'NEWTON RD', 'TAMPINES', '8 TUALINK',
       'JITERMINAL', 'CHUAN LI', '18PIONEER', 'TPJPEIRCPC', '24JRPORT',
       'UNKNOWN YD', '26 TG KLIN', '51 BANYAN', 'VOPAK SAKR',
       '52 S KADUT', '21 GUL AVE', '12 SAKRA', 'COGENT TEM', '20TUAS ST',
       '100 BANYAN', '7GULDRIVE', '9 CHIN BEE', '17TUASVWCIR', 'PDP1',
       '21PANDANAV', '14TUAS', '8GUL RD', '300 AYER M', 'XXXXXXX',
       '60 TUAS', 'TBS STOLT', '9B J PIER', 'PTCJI WH', 'COGENT CS',
       'GREEN Y2', 'ECO TUAS', 'ENG LEE ', 'JURONG P', '132PIONEER',
       '3PASIRRISD12', '31GUL CRES', '21SKARAAVE', '24PENJURUR', 'ECOLAB',
       '1TUAS', '41TUASROAD', '61SERAYAAV', '9TUASBASINLNK', '4BENOIRD',
       '14 TUAS', '9TUASAVE10', '11 TUAS', 'ISLAND PAC', '10TUASSOUT',
       '15TUASAVE6', '6TUAS', '39BENOIRD', '10TUAS AVE', '10 TUAS',
       '5 TUAS AVE', 'PSA W HSE', '5TUAS VIEW', '23TEMBUSURD', 'ECO TANK',
       'YARD 3', '7 GUL CIR', 'CWT JALAN', '10TUASAVE13', '38GULAVE',
       '37TUAS', '11TUASAVE11', '1B SAKRA', '9 PIONEER', '31 JURONG',
       '31JUR PORT', '39AYERMERD', '4 BENOI', 'YANGKEE', '38GUL AVE',
       '76PIONERRD', '47JLNBUROH', '9KALLANGSEC', 'AIK MOH', '31J PORT',
       'NRS W HSE', 'HB 48P', '111SAKRA', '47A JBUROH', 'COG TANK',
       '21 LYANG', 'W SHOP JI', '6TUAS AVE1', '31JPORT 04',
       '49PANDAN 03 02', '19TUAS', 'PPW', 'PTCISL TT', '40PANDANRD',
       '43GULDRIVE', 'PIONEER YD', '701AYERMER', '30 PIONEER',
       '76 PIONEER', '20 TUAS 13', 'BUROH STRT', '20TUAS13', 'PTCJID',
       'VOPAK PJ', '18PIONEER ', '5ATOHGUANRD', 'ODSA PAC', '8 TUAS',
       '58TUASBAS', '18TUASLINK', '42PANDAN1', '9 J PIER 1', '9PIONEERVW',
       '24JURPORT', '42PANDAN5', 'ETPC1', 'PSATUAS', 'SUMITOMO',
       '37 TUAS', '76PIONEER', 'HB CLMTI', 'TPCAR PK C', '11TUASLINK1',
       '48 TUAS A9', '25 SENOKO', '6 TUAS AVE', '180GUL CIR',
       '2JURONGPOR', 'REJOICE CO', 'JIDTR', '1 BANYAN P', '23TUAS',
       '18PIONRD', 'ALLIED2', 'CDC CLEMEN', '37TUASAVE8', '6TUASAVE2',
       '33PENJURU', '47TUASVIEW', '75TUASSOUTH', '33PENJURUL', 'TEMBUSU',
       '1 TUASBAYCLOSE', 'CGC', '33 PENJURU', '24PENJURU', '35TUASRD',
       '23 TUAS', '1 BANYAN', '39B JLN', '37TUASAVE2', '16 TUAS',
       'ALLIED 1', 'AVE 7', '30PIONEERD', '6 FISHERY', 'JOO KOON',
       'JI OFFLOAD', '24P JURU PSA', 'ENTERPRISE', '50TUASAVE9',
       'PSA PPT', 'PSA BT KT', 'PSA TUAS', 'CWT TUAS', 'SKY COGENT',
       '352BOONLAY', '7 TUAS A14', 'CWT PIONEER', '48TOHGUADR',
       'CWT47JLNBUROH', '1BANYAN P', 'CANCEL TRIP', 'KD', 'ISLD RTG  G ',
       '1TEMBUSUCR', 'PTC JID', 'PTC ISL  G ', 'PTC MER GROUND',
       'PTC MER PARK', 'HB NX5', 'CARPARK C  NX5 ', 'COGENT TANK 15',
       'COGENT TEMBUSU', 'PTC ISLAND PARK', 'JI W SHOP', 'GREASE PL',
       'STARTFIRST', '11SCIENCEP', 'GKE', '9GULCIRCLE', '21PIONEERS',
       '1PANDAN RD', 'PPW BLK2', 'CARPARK C NX5 ', 'TRANSIT PANDAN',
       'JURONG PORT', '1 ANGSANA', '2BUROHCRESCENT', '20 TUAS',
       'SKY COG LOGIST', '21 BANYAN', '20TUAS', '8 10 GUL', 'PTC HUB G ',
       '12TGPENJUR', 'TONGCNTR', '7 GUL AVE', 'SILTRONICSILI',
       'SGINTEGRATED', 'SHELLPANDAN', '200AYERMB', '10PANDANAV',
       '31 GUL CIR', '6 TOHGUAN', 'POSAN', 'PTC ISLAND  SHED ',
       '6PIONEER', 'FAIRCHEM', '35 KIAN TE', 'LS MODULAR', 'TPC2 G ',
       'TPC1 G ', 'CWT HUB', 'PSASEMBAWA', '1JLNBESUT', 'CONTCONN',
       'MATCHBOX', '11 JLN TER', '52TG PENJ', '52 TG  PEN', '1SENOKOAVE'],
      dtype=object)

# Current Unique 1-1 Locations

In [10]:
unique_trip_count = df.groupby(['FROMLOCSTR', 'TOLOCSTR']).size().count()
print(unique_trip_count)

7921

## Fuzzy Matching using Token Set Ratio

In [11]:
# calculate Levenshtein distance between two strings, considering set intersections
def levenshtein_distance(s1, s2):
    return fuzz.token_set_ratio(s1, s2)

THRESHOLD = 75

def group_similar_addresses(df):
    grouped_addresses = {}
    for from_loc in df['FROMLOCSTR'].unique():
        similar_addresses = [from_loc]  # Include itself in the group
        for address in grouped_addresses.keys():
            similarity = levenshtein_distance(from_loc, address)
            if similarity >= THRESHOLD:
                similar_addresses.append(address)
        for address in similar_addresses:
            grouped_addresses[address] = similar_addresses
    return grouped_addresses

similar_address_groups = group_similar_addresses(df)

def assign_corrected_address(from_loc):
    for correct_address, similar_addresses in similar_address_groups.items():
        if from_loc in similar_addresses:
            return correct_address

# lambda function with .apply() speeds up the process
df['CORRECTFROM'] = df['FROMLOCSTR'].apply(lambda x: assign_corrected_address(x))

df['CORRECTTO'] = df['TOLOCSTR'].apply(lambda x: assign_corrected_address(x))

df

,OrderNumber,CUSTID,JOBTYPE,Department,FROMLOCSTR,TOLOCSTR,STARTTM,ENDTM,TripDuration,CTCOMPLETEDT,...,TrailerId,JOINED DATE,RESIGNED DATE,RACE,Team,Status,AGE_Years,Seniority,CORRECTFROM,CORRECTTO
0,TL9008453,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-07 08:00:00,2021-01-07 08:30:00,0.500000,2021-01-07,...,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,16.0,53.58,13.72,JI DRUM,1 SEARAYA
1,TL9008453,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-07 10:30:00,2021-01-07 11:00:00,0.500000,2021-01-07,...,972.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,16.0,53.58,13.72,JI DRUM,1 SEARAYA
2,TL9009105,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-27 08:00:00,2021-01-27 08:30:00,0.500000,2021-01-27,...,972.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,6.0,53.58,13.72,JI DRUM,1 SEARAYA
3,TL9009105,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-27 10:30:00,2021-01-27 11:00:00,0.500000,2021-01-27,...,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,6.0,53.58,13.72,JI DRUM,1 SEARAYA
4,TL9008550,00-RE001,LOCAL,CHIEN,JI DRUM,1 SERAYA AVE,2021-01-11 08:00:00,2021-01-11 08:30:00,0.500000,2021-01-11,...,1538.0,2007-06-07,2021-02-23,CHINESE,CHIEN LI,13.0,53.58,13.72,JI DRUM,1 SEARAYA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1081779,TE8037442,00-RA186,EXPORT,MAIN,PTC48 G,42PANDAN1,2023-12-06 09:50:00,2023-12-06 10:00:00,0.166667,2023-12-06,...,1772.0,2008-03-17,2023-12-31,CHINESE,FCL,34.0,51.33,15.79,PTC48 G,48PANDAN
1081780,TL9050450,00-RA186,LOCAL,CHIEN,COGENT TANK 15,48DRUMMING,2023-12-04 10:30:00,2023-12-04 12:00:00,1.500000,2023-12-04,...,119.0,2004-06-25,2023-12-31,CHINESE,CHIEN LI,8.0,68.25,19.52,COGENT TANK 15,48DRUMMING
1081781,TL9050450,00-RA186,LOCAL,CHIEN,48DRUMMING,STOLT NEL,2023-12-06 05:39:00,2023-12-06 05:59:00,0.333333,2023-12-06,...,119.0,2008-08-22,2023-05-10,CHINESE,CHIEN LI,21.0,39.08,14.71,48DRUMMING,STOLT NEL
1081782,TE8037521,00-RA186,EXPORT,MAIN,42PANDAN1,PSA PPT,2023-12-13 09:30:00,2023-12-13 10:30:00,1.000000,2023-12-13,...,1937.0,2000-11-20,2022-10-02,CHINESE,FCL,8.0,58.92,21.86,48PANDAN,PPT
1081783,XE7047519,00-RP036,EXPORT,XINHUA,CONT CONN,PTC MER GROUND,2023-12-29 00:00:00,2023-12-29 00:00:00,0.000000,2023-12-29,...,NaN,NaN,2023-12-31,NaN,NaN,NaN,NaN,NaN,CONT CONN,MER GROUND

# New number of Unique 1-1 Combinations

In [12]:
unique_trip_count = df.groupby(['CORRECTFROM', 'CORRECTTO']).size().count()
print(unique_trip_count)

4741

# Saving Final DataFrame

In [13]:
df.to_csv(FINAL_SHEET, index=False)